"""auth tokens verification and indexes

Revision ID: d40538205491
Revises: de22525b318c
Create Date: 2026-08-14 23:33:24.313126

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d40538205491"
down_revision: str | Sequence[str] | None = "de22525b318c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_applications_candidate_id_created", "applications", ["candidate_id", "created_at"], unique=False
    )
    op.create_index("ix_applications_job_id_status", "applications", ["job_id", "status"], unique=False)
    op.create_index(op.f("ix_candidate_profiles_user_id"), "candidate_profiles", ["user_id"], unique=True)
    op.create_index("ix_jobs_admin_id_status", "jobs", ["admin_id", "status"], unique=False)
    op.create_index("ix_jobs_experience_level", "jobs", ["experience_level"], unique=False)
    op.create_index("ix_jobs_status_created_at", "jobs", ["status", "created_at"], unique=False)
    op.add_column("users", sa.Column("email_verified_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("token_version", sa.Integer(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "token_version")
    op.drop_column("users", "email_verified_at")
    op.drop_index("ix_jobs_status_created_at", table_name="jobs")
    op.drop_index("ix_jobs_experience_level", table_name="jobs")
    op.drop_index("ix_jobs_admin_id_status", table_name="jobs")
    op.drop_index(op.f("ix_candidate_profiles_user_id"), table_name="candidate_profiles")
    op.drop_index("ix_applications_job_id_status", table_name="applications")
    op.drop_index("ix_applications_candidate_id_created", table_name="applications")
    # ### end Alembic commands ###
